name: dev cicd
on: 
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'docker-compose.yml'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # 执行 git pull

      # 将本机的私钥复制到执行github action的ubuntu服务器上, 以使action服务器可以免密与测试服务器进行ssh通信
      # ssh-keyscan 是将测试机ip加入ssh信任, 防止再提示指纹确认
      - name: set ssh key 
        run: | 
          mkdir -p ~/.ssh/
          echo "${{secrets.MAGICBOOK_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "124.223.206.155" >> ~/.ssh/known_hosts 
      
      - name: deploy 
        run: |
          ssh weiyi@124.223.206.155 "
            cd ~/workspace
            git clone https://github.com/wangweiyi/github-action-vue-demo.git -b dev
            git checkout dev
            git pull origin dev
            # 启动docker 
            docker-compose build vue-demo
            docker-compose up -d
          "
      
      - name: delete ssh key
        run: rm -rf ~/.ssh/id_rsa

